pub const LOCAL_FEE: u128 = 100;
pub const ARBITRATION_FEE: u128 = 10;
pub const OFFERS_QUERY_PROFILES_LIMIT: u32 = 10;
pub const OFFERS_QUERY_OFFERS_BY_PROFILE: u32 = 3;
pub const PROFILE_QUERY_LAST_TRADE_THRESHOLD: u64 = 60 * 60 * 24 * 14; // 2 weeks
pub const BASE_ORACLE_DENOM: &str = "ATOM";
