// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Arbitration: typeof import('./ui/pages/Arbitration.vue')['default']
    ArchivedOfferItem: typeof import('./ui/components/myOffers/ArchivedOfferItem.vue')['default']
    BaseIcon: typeof import('./ui/components/commons/BaseIcon.vue')['default']
    CollapsedMakerOffer: typeof import('./ui/components/maker/CollapsedMakerOffer.vue')['default']
    CollapsedMyOffer: typeof import('./ui/components/myOffers/CollapsedMyOffer.vue')['default']
    CollapsedOffer: typeof import('./ui/components/offers/CollapsedOffer.vue')['default']
    CreateOffer: typeof import('./ui/components/offers/CreateOffer.vue')['default']
    CurrencyInput: typeof import('./ui/components/CurrencyInput.vue')['default']
    CustomSelect: typeof import('./ui/components/commons/CustomSelect.vue')['default']
    ExpandedMakerOffer: typeof import('./ui/components/maker/ExpandedMakerOffer.vue')['default']
    ExpandedMyOffer: typeof import('./ui/components/myOffers/ExpandedMyOffer.vue')['default']
    ExpandedOffer: typeof import('./ui/components/offers/ExpandedOffer.vue')['default']
    Header: typeof import('./ui/components/Header.vue')['default']
    Home: typeof import('./ui/pages/Home.vue')['default']
    HomeHero: typeof import('./ui/components/HomeHero.vue')['default']
    IconDone: typeof import('./ui/components/commons/IconDone.vue')['default']
    IconTooltip: typeof import('./ui/components/commons/IconTooltip.vue')['default']
    ListContentResult: typeof import('./ui/components/commons/ListContentResult.vue')['default']
    ListDisputes: typeof import('./ui/components/arbitration/ListDisputes.vue')['default']
    ListMakerOffers: typeof import('./ui/components/maker/ListMakerOffers.vue')['default']
    ListMyOffers: typeof import('./ui/components/myOffers/ListMyOffers.vue')['default']
    ListOffers: typeof import('./ui/components/offers/ListOffers.vue')['default']
    Loading: typeof import('./ui/components/commons/Loading.vue')['default']
    Maker: typeof import('./ui/pages/Maker.vue')['default']
    Modal: typeof import('./ui/components/commons/Modal.vue')['default']
    ModalLoading: typeof import('./ui/components/commons/ModalLoading.vue')['default']
    NavDesktop: typeof import('./ui/components/NavDesktop.vue')['default']
    NavMobile: typeof import('./ui/components/NavMobile.vue')['default']
    NotificationWidget: typeof import('./ui/components/commons/NotificationWidget.vue')['default']
    NotificationWidgetMobile: typeof import('./ui/components/commons/NotificationWidgetMobile.vue')['default']
    Offers: typeof import('./ui/pages/Offers.vue')['default']
    OpenDisputeItem: typeof import('./ui/components/arbitration/OpenDisputeItem.vue')['default']
    RightArrow: typeof import('./ui/components/commons/RightArrow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TradeAction: typeof import('./ui/components/tradeDetail/TradeAction.vue')['default']
    TradeActions: typeof import('./ui/components/tradeDetail/TradeActions.vue')['default']
    TradeDetail: typeof import('./ui/pages/TradeDetail.vue')['default']
    TradeHistoryItem: typeof import('./ui/components/trades/TradeHistoryItem.vue')['default']
    TradeOpenItem: typeof import('./ui/components/trades/TradeOpenItem.vue')['default']
    Trades: typeof import('./ui/pages/Trades.vue')['default']
    WalletButton: typeof import('./ui/components/commons/WalletButton.vue')['default']
    WalletWidget: typeof import('./ui/components/commons/WalletWidget.vue')['default']
  }
}

export {}
