[package]
name = "localterra-protocol"
version = "1.0.0"
authors = ["LocalTerra Developers"]
edition = "2018"
description = "Common helpers for localterra-protocol"
license = "Apache-2.0"
repository = "https://github.com/Local-Terra/localterra-contracts"
homepage = "https://localterra.money"
documentation = "https://docs.localterra.money"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.8.0" }
cosmwasm-std = { version = "0.16.0" }
cosmwasm-storage = { version = "0.16.0" }
cw-storage-plus = "0.9.1"
schemars = "0.8.10"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terra-cosmwasm = { version = "2.2.0" }
thiserror = "1.0.25"
astroport = { path = "../astroport", default-features = false }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
cosmwasm-vm = { version = "0.16.0" }
